### ISSUE TITLE
Permission denied to `apt-get update` in container `plone6-frontend` 

### ISSUE THREAD

**Issue by me-kell** [plone/plone-frontend#27]
**To reproduce it**:

```console
$ sudo docker run \
    --name plone6-frontend \
    --link plone6-backend:backend \
    -e RAZZLE_API_PATH=http://localhost:8080/Plone \
    -e RAZZLE_INTERNAL_API_PATH=http://backend:8080/Plone \
    -d \
    -p 3000:3000 \
    plone/plone-frontend:latest

$ sudo docker exec -it plone6-frontend bash

$ apt-get update
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```
**Workaround**:

Run with the clean-up option (`--rm`) and user `root` (`--user 0`)
```console

$ sudo docker run \
    --rm --user 0 \    
    --name plone6-frontend \
    --link plone6-backend:backend \
    -e RAZZLE_API_PATH=http://localhost:8080/Plone \
    -e RAZZLE_INTERNAL_API_PATH=http://backend:8080/Plone \
    -d \
    -p 3000:3000 \
    plone/plone-frontend:latest
```

**Comment by davisagli** [comment]
@me-kell This is working as intended. The frontend container runs as the `node` user by default. It is not a good security practice to run containers as root by default.

Your workaround is fine, but it is a little strange to be manually running apt in a container, because the changes will be lost when you update to a newer version of the plone-frontend image. Instead, you should be creating your own Dockerfile to build an image that extends the plone-frontend image. Then you have a way to easily rebuild when a new version of the plone-frontend image is available.

**Comment by me-kell** [comment]
@davisagli Thanks. I understand.
